In [ ]:
#RNN
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

tf.__version__

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df['sentiment'] = df['sentiment'].map({'positive': 1,'negative': 0})

In [4]:
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [5]:
x = df['review']
y = df['sentiment']

In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(x)

x_seq = tokenizer.texts_to_sequences(x)

In [18]:
max_length = 100

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_pad = pad_sequences(x_seq, max_length)

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_pad, y, test_size=0.2, random_state=4)

In [21]:
x = layers.Input(shape=(max_length,1))
cell = [
    layers.SimpleRNNCell(32, activation='tanh'),
    layers.SimpleRNNCell(64, activation='tanh'),
    layers.SimpleRNNCell(128, activation='tanh')]
rnn = layers.RNN(cell)
rnn_output = rnn(x)
output = layers.Dense(1, activation='sigmoid')(rnn_output)
model = keras.Model(inputs=x, outputs=output)

In [22]:
model.compile(loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 100, 1)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ rnn_1 (RNN)                          │ (None, 128)                 │          32,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 32,129 (125.50 KB)

 Trainable params: 32,129 (125.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(x_train, y_train, epochs=50, verbose=2, validation_data=(x_test, y_test))

Epoch 1/50
1250/1250 - 128s - 102ms/step - accuracy: 0.4919 - loss: 0.7001 - val_accuracy: 0.5036 - val_loss: 0.6939
Epoch 2/50
1250/1250 - 81s - 65ms/step - accuracy: 0.5016 - loss: 0.6958 - val_accuracy: 0.5029 - val_loss: 0.6932
Epoch 3/50
1250/1250 - 101s - 81ms/step - accuracy: 0.5035 - loss: 0.6959 - val_accuracy: 0.5240 - val_loss: 0.6910
Epoch 4/50
1250/1250 - 76s - 61ms/step - accuracy: 0.5098 - loss: 0.6950 - val_accuracy: 0.5009 - val_loss: 0.6923
Epoch 5/50
1250/1250 - 73s - 58ms/step - accuracy: 0.5164 - loss: 0.6947 - val_accuracy: 0.5037 - val_loss: 0.7005
Epoch 6/50
1250/1250 - 93s - 75ms/step - accuracy: 0.5128 - loss: 0.6943 - val_accuracy: 0.5184 - val_loss: 0.6933
Epoch 7/50
1250/1250 - 63s - 50ms/step - accuracy: 0.5209 - loss: 0.6939 - val_accuracy: 0.5223 - val_loss: 0.6924
Epoch 8/50
1250/1250 - 62s - 49ms/step - accuracy: 0.5247 - loss: 0.6930 - val_accuracy: 0.5376 - val_loss: 0.6934
Epoch 9/50
1250/1250 - 63s - 50ms/step - accuracy: 0.5292 - loss: 0.6922 - val_accuracy: 0.5281 - val_loss: 0.6912
Epoch 10/50
1250/1250 - 76s - 61ms/step - accuracy: 0.5289 - loss: 0.6923 - val_accuracy: 0.5150 - val_loss: 0.6925
Epoch 11/50
1250/1250 - 60s - 48ms/step - accuracy: 0.5305 - loss: 0.6910 - val_accuracy: 0.5348 - val_loss: 0.6890
Epoch 12/50
1250/1250 - 59s - 47ms/step - accuracy: 0.5339 - loss: 0.6909 - val_accuracy: 0.5360 - val_loss: 0.6917
Epoch 13/50
1250/1250 - 58s - 46ms/step - accuracy: 0.5343 - loss: 0.6910 - val_accuracy: 0.5086 - val_loss: 0.7007
Epoch 14/50
1250/1250 - 57s - 45ms/step - accuracy: 0.5340 - loss: 0.6910 - val_accuracy: 0.5445 - val_loss: 0.6885
Epoch 15/50
1250/1250 - 86s - 69ms/step - accuracy: 0.5370 - loss: 0.6903 - val_accuracy: 0.5388 - val_loss: 0.6894
Epoch 16/50
1250/1250 - 65s - 52ms/step - accuracy: 0.5339 - loss: 0.6906 - val_accuracy: 0.5181 - val_loss: 0.7029
Epoch 17/50
1250/1250 - 61s - 49ms/step - accuracy: 0.5301 - loss: 0.6913 - val_accuracy: 0.5086 - val_loss: 0.6973
Epoch 18/50
1250/1250 - 54s - 43ms/step - accuracy: 0.5374 - loss: 0.6901 - val_accuracy: 0.5048 - val_loss: 0.7063
Epoch 19/50
1250/1250 - 74s - 59ms/step - accuracy: 0.5334 - loss: 0.6908 - val_accuracy: 0.5475 - val_loss: 0.6877
Epoch 20/50
1250/1250 - 76s - 60ms/step - accuracy: 0.5415 - loss: 0.6890 - val_accuracy: 0.5394 - val_loss: 0.6899
Epoch 21/50
1250/1250 - 64s - 51ms/step - accuracy: 0.5454 - loss: 0.6889 - val_accuracy: 0.5396 - val_loss: 0.6887
Epoch 22/50
1250/1250 - 68s - 54ms/step - accuracy: 0.5282 - loss: 0.6912 - val_accuracy: 0.5356 - val_loss: 0.6892
Epoch 23/50
1250/1250 - 87s - 69ms/step - accuracy: 0.5370 - loss: 0.6901 - val_accuracy: 0.5392 - val_loss: 0.6938
Epoch 24/50
1250/1250 - 77s - 62ms/step - accuracy: 0.5379 - loss: 0.6904 - val_accuracy: 0.5497 - val_loss: 0.6875
Epoch 25/50
1250/1250 - 90s - 72ms/step - accuracy: 0.5401 - loss: 0.6894 - val_accuracy: 0.5252 - val_loss: 0.6956
Epoch 26/50
1250/1250 - 79s - 63ms/step - accuracy: 0.5333 - loss: 0.6903 - val_accuracy: 0.5400 - val_loss: 0.6944
Epoch 27/50
1250/1250 - 79s - 63ms/step - accuracy: 0.5426 - loss: 0.6889 - val_accuracy: 0.5525 - val_loss: 0.6850
Epoch 28/50
1250/1250 - 100s - 80ms/step - accuracy: 0.5383 - loss: 0.6899 - val_accuracy: 0.5263 - val_loss: 0.6949
Epoch 29/50
1250/1250 - 93s - 74ms/step - accuracy: 0.5429 - loss: 0.6886 - val_accuracy: 0.5461 - val_loss: 0.6908
Epoch 30/50

In [ ]:
def plot_results(history):
    results = pd.DataFrame({"Train Loss": history.history['loss'], "Validation Loss": history.history['val_loss'],
              "Train Accuracy": history.history['accuracy'], "Validation Accuracy": history.history['val_accuracy']
             })
    fig, ax = plt.subplots(nrows=2, figsize=(16, 9))
    results[["Train Loss", "Validation Loss"]].plot(ax=ax[0])
    results[["Train Accuracy", "Validation Accuracy"]].plot(ax=ax[1])
    ax[0].set_xlabel("Epoch")
    ax[1].set_xlabel("Epoch")
    plt.show()

In [ ]:
#acc visualization
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Accuracy Graph")
plt.show()

In [ ]:
#loss visualization
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss Graph")
plt.show()